name: playbook_ui
description: Playbook UI package.
version: 0.0.3+1
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency
  playbook: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
