name: playbook_generator
description: Playbook Generator Package
version: 0.0.4
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  build: ^2.0.0
  source_gen: ^1.0.0
  path: ^1.8.0
  glob: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
