name: playbook_generator
description: Playbook Generator Package
version: 0.0.6+1
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.5.0
  path: ^1.8.3
  glob: ^2.1.2
  code_builder: ^4.9.0
  dart_style: ^2.3.4

dev_dependencies:
  very_good_analysis: ^5.1.0
