name: playbook_snapshot
description: Playbook Snapshot package.
version: 0.0.2
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  playbook: ^0.0.2
  platform: ^3.0.0
  file: ^6.1.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
