name: playbook_snapshot
description: Playbook Snapshot package.
version: 0.2.1
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  playbook: ^0.0.4
  yaml: ^3.1.2

dev_dependencies:
  very_good_analysis: ^5.1.0
