name: generator_app
description: Sample app
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  playbook:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  playbook_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/flutter.png

dependency_overrides:
  playbook:
    path: ../../../playbook
  playbook_generator:
    path: ../../../playbook_generator
